spring:
  main:
    web-application-type: servlet
  datasource:
    hikari:
      maximum-pool-size: 10

server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

whatsappka:
  security:
    jwt-secret: ${JWT_SECRET:}
    refresh-cookie-secure: ${REFRESH_COOKIE_SECURE:true}
    bcrypt-strength: ${BCRYPT_STRENGTH:10}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  override-with-generic-response: false
